### ISSUE TITLE
master and last gem version different code

### ISSUE THREAD

**Issue by rsl** [iGEL/it#19]
hi. i'm making a pull request for a tiny change  and noticed that lib/it/interpolation.rb is pretty different between master and 0.8.0 [the last gem version]. seems like this was 2 years ago also. is there a chance of getting a gem update? not sure where i should make this change [as it's in the very code that's in different places] and i use the last gem release not git [master] in my gemfile. thanks.

**Comment by iGEL** [comment]
I just released 1.0.0
