### ISSUE TITLE
Passing a html_safe href to It.it raises `Invalid href given`

### ISSUE THREAD

**Issue by JamesBalazs** [iGEL/it#25]
Our app is passing pre-built html tags to `It.it` as interpolated variables, but to get these to render on the frontend and not be escaped by It we have to call `html_safe` on every variable we pass to It in a method.

However, with normal hrefs (not HTML we've already built) we get `invalid href given` from It, due to this line:
`raise TypeError, 'Invalid href given' unless [Hash, String].include?(href.class)`

We can solve this problem by adding `ActiveSupport::SafeBuffer` to the array in the conditional, and it doesn't seem to cause any other errors in our test suite.

Is there any reason you don't consider an html safe string a valid href?

If not, can `ActiveSupport::SafeBuffer` be added to the array of valid types in the gem, so we don't have to use a workaround/override the method ourselves?

**Comment by james-balazs1** [comment]
This is a similar use case to #24

**Comment by iGEL** [comment]
Thanks for reporting. I didn't yet had the to review it, but could you maybe provide a failing spec for this?

**Comment by james-balazs1** [comment]
Something along the lines of:

### config/locales/en.yml
```
en:
   translation_with_link: Translation with %{link:%{link_name}}
```
### test_subject.rb
```
link = "http://www.github.com/iGEL/it/"
It.it("translation_with_link", link: link.html_safe, link_name: "Link")
```

should raise the same error. As you can pass html safe strings as normal variables not links, it would be nice for the type check to allow a href for a link through if it has already been marked as safe elsewhere.

Thanks.
